import type { ChatMessage, GymPost, GymStory, GymUser, SocialState } from "./types";

export const currentUserId = "user-edu";

export const workoutImagePool = [
  "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=900&q=86",
  "https://images.unsplash.com/photo-1517964603305-11c0f6f66012?auto=format&fit=crop&w=900&q=86",
  "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=900&q=86",
  "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=900&q=86",
];

const users: Record<string, GymUser> = {
  "user-edu": {
    id: "user-edu",
    name: "Eduardo",
    username: "edu.fit",
    accent: "var(--gc-brand)",
    avatarUrl: null,
    bio: "Lifestyle fitness, consistência e treino cedo.",
    goal: "Consistencia",
    instagramUsername: "edu.fit",
    birthDate: "1996-05-07",
    sports: ["Musculacao", "Corrida", "Funcional"],
    location: "Recife",
    gyms: ["Pulse Club Recife", "Wellness Lab"],
    preferredTimes: ["manhã", "noite"],
    currentStreak: 6,
    longestStreak: 21,
    lastWorkoutDate: "2026-05-05",
    workoutsThisMonth: 5,
    activeDaysCount: 31,
    checkInsCount: 42,
    achievements: ["21d recorde", "Manhã forte", "Pulse regular"],
    followersCount: 1284,
    followingCount: 318,
    isFollowing: true,
    followStatus: "accepted",
    isPrivate: false,
    workoutDays: [
      "2026-03-01",
      "2026-03-02",
      "2026-03-03",
      "2026-03-04",
      "2026-03-05",
      "2026-03-06",
      "2026-03-07",
      "2026-03-08",
      "2026-03-09",
      "2026-03-10",
      "2026-03-11",
      "2026-03-12",
      "2026-03-13",
      "2026-03-14",
      "2026-03-15",
      "2026-03-16",
      "2026-03-17",
      "2026-03-18",
      "2026-03-19",
      "2026-03-20",
      "2026-03-21",
      "2026-04-24",
      "2026-04-25",
      "2026-04-26",
      "2026-04-30",
      "2026-05-01",
      "2026-05-02",
      "2026-05-03",
      "2026-05-04",
      "2026-05-05",
    ],
  },
  "user-maya": {
    id: "user-maya",
    name: "Maya Lima",
    username: "maya.move",
    accent: "var(--gc-consistency-month)",
    avatarUrl: null,
    bio: "Treino inteligente, corrida e mobilidade.",
    goal: "Performance leve",
    location: "Recife",
    gyms: ["Wellness Lab", "Pulse Club Recife"],
    preferredTimes: ["noite"],
    currentStreak: 12,
    longestStreak: 18,
    lastWorkoutDate: "2026-05-06",
    workoutsThisMonth: 14,
    activeDaysCount: 64,
    checkInsCount: 39,
    achievements: ["Mobilidade", "12d vivos", "Wellness crew"],
    followersCount: 892,
    followingCount: 201,
    isFollowing: true,
    followStatus: "accepted",
    isPrivate: false,
    workoutDays: [],
  },
  "user-rafa": {
    id: "user-rafa",
    name: "Rafa Costa",
    username: "rafa.strength",
    accent: "var(--gc-blue)",
    avatarUrl: null,
    bio: "Força, hipertrofia e café antes das 7.",
    goal: "Hipertrofia",
    location: "Recife",
    gyms: ["Pulse Club Recife"],
    preferredTimes: ["manhã"],
    currentStreak: 9,
    longestStreak: 16,
    lastWorkoutDate: "2026-05-06",
    workoutsThisMonth: 11,
    activeDaysCount: 52,
    checkInsCount: 31,
    achievements: ["Forca limpa", "Push regular", "9d streak"],
    followersCount: 542,
    followingCount: 180,
    isFollowing: true,
    followStatus: "accepted",
    isPrivate: false,
    workoutDays: [],
  },
  "user-bia": {
    id: "user-bia",
    name: "Bia Nunes",
    username: "bia.run",
    accent: "var(--gc-consistency-year)",
    avatarUrl: null,
    bio: "Corrida, funcional e domingo ativo.",
    goal: "Corrida 10K",
    location: "Olinda",
    gyms: ["Studio Flow", "Pulse Club Recife"],
    preferredTimes: ["tarde"],
    currentStreak: 5,
    longestStreak: 12,
    lastWorkoutDate: "2026-05-06",
    workoutsThisMonth: 9,
    activeDaysCount: 47,
    checkInsCount: 26,
    achievements: ["5K club", "Domingo ativo", "Flow"],
    followersCount: 721,
    followingCount: 255,
    isFollowing: false,
    followStatus: "none",
    isPrivate: false,
    workoutDays: [],
  },
  "user-leo": {
    id: "user-leo",
    name: "Leo Martins",
    username: "leo.daily",
    accent: "var(--gc-consistency-daily)",
    avatarUrl: null,
    bio: "Um treino por dia, sem drama.",
    goal: "Consistencia",
    location: "Recife",
    gyms: ["Pulse Club Recife"],
    preferredTimes: ["noite"],
    currentStreak: 32,
    longestStreak: 45,
    lastWorkoutDate: "2026-05-06",
    workoutsThisMonth: 19,
    activeDaysCount: 118,
    checkInsCount: 87,
    achievements: ["Lendario", "Sem falhar", "Cardio social"],
    followersCount: 1103,
    followingCount: 390,
    isFollowing: false,
    followStatus: "none",
    isPrivate: false,
    workoutDays: [],
  },
  "user-ana": {
    id: "user-ana",
    name: "Ana Torres",
    username: "ana.core",
    accent: "var(--gc-consistency-mid)",
    avatarUrl: null,
    bio: "Pilates, forca e rotina limpa.",
    goal: "Definicao",
    location: "Recife",
    gyms: ["Wellness Lab"],
    preferredTimes: ["manhã"],
    currentStreak: 4,
    longestStreak: 15,
    lastWorkoutDate: "2026-05-05",
    workoutsThisMonth: 7,
    activeDaysCount: 44,
    checkInsCount: 28,
    achievements: ["Core forte", "Wellness", "Pilates"],
    followersCount: 438,
    followingCount: 144,
    isFollowing: false,
    followStatus: "none",
    isPrivate: false,
    workoutDays: [],
  },
  "user-caio": {
    id: "user-caio",
    name: "Caio Freire",
    username: "caio.lift",
    accent: "var(--gc-blue)",
    avatarUrl: null,
    bio: "Leg day sem desculpa.",
    goal: "Forca",
    location: "Recife",
    gyms: ["Iron House"],
    preferredTimes: ["noite"],
    currentStreak: 3,
    longestStreak: 10,
    lastWorkoutDate: "2026-05-05",
    workoutsThisMonth: 6,
    activeDaysCount: 29,
    checkInsCount: 18,
    achievements: ["Leg day", "Iron", "Voltou"],
    followersCount: 312,
    followingCount: 98,
    isFollowing: false,
    followStatus: "none",
    isPrivate: false,
    workoutDays: [],
  },
  "user-nina": {
    id: "user-nina",
    name: "Nina Alves",
    username: "nina.fitclub",
    accent: "var(--gc-consistency-mid)",
    avatarUrl: null,
    bio: "Treino, comunidade e check-ins.",
    goal: "Lifestyle",
    location: "Boa Viagem",
    gyms: ["Studio Flow"],
    preferredTimes: ["tarde", "noite"],
    currentStreak: 6,
    longestStreak: 14,
    lastWorkoutDate: "2026-05-06",
    workoutsThisMonth: 10,
    activeDaysCount: 58,
    checkInsCount: 35,
    achievements: ["Lifestyle", "Check-in pro", "Flow crew"],
    followersCount: 677,
    followingCount: 211,
    isFollowing: false,
    followStatus: "none",
    isPrivate: false,
    workoutDays: [],
  },
};

const comments = {
  "comment-1": {
    id: "comment-1",
    postId: "post-1",
    userId: "user-rafa",
    body: "Push day nesse horario e outro nivel.",
    createdAt: "2026-05-06T07:31:00",
  },
  "comment-2": {
    id: "comment-2",
    postId: "post-1",
    userId: "user-maya",
    body: "Streak bonito demais.",
    createdAt: "2026-05-06T07:44:00",
  },
  "comment-3": {
    id: "comment-3",
    postId: "post-2",
    userId: "user-edu",
    body: "Foi mesmo. Consistência absurda.",
    createdAt: "2026-05-06T18:53:00",
  },
};

const posts: GymPost[] = [
  {
    id: "post-1",
    userId: "user-edu",
    imageUrl:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    caption: "Treino cedo, mente limpa. Peito, ombro e triceps fechados.",
    workoutType: "Push day",
    gymName: "Pulse Club Recife",
    gymId: "gym-pulse",
    locationSource: "gym",
    locationName: "Pulse Club Recife",
    locationLatitude: null,
    locationLongitude: null,
    locationGoogleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Pulse+Club+Recife",
    createdAt: "2026-05-05T07:18:00",
    workoutDate: "2026-05-05",
    isWorkoutPost: true,
    streakAtPost: 6,
    likesCount: 1284,
    likedByCurrentUser: false,
    comments: [comments["comment-1"], comments["comment-2"]],
  },
  {
    id: "post-2",
    userId: "user-maya",
    imageUrl:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    caption: "Hoje foi sem pressa, mas foi.",
    workoutType: "Full body",
    gymName: "Localização atual",
    gymId: "",
    locationSource: "current",
    locationName: "Localização atual",
    locationLatitude: -8.1211,
    locationLongitude: -34.9006,
    locationGoogleMapsUrl: "https://www.google.com/maps/search/?api=1&query=-8.1211%2C-34.9006",
    createdAt: "2026-05-06T18:42:00",
    workoutDate: "2026-05-06",
    isWorkoutPost: true,
    streakAtPost: 12,
    likesCount: 892,
    likedByCurrentUser: true,
    comments: [comments["comment-3"]],
  },
  {
    id: "post-3",
    userId: "user-leo",
    imageUrl:
      "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    caption: "Cardio leve para manter a sequencia lendaria viva.",
    workoutType: "Cardio",
    gymName: "Pulse Club Recife",
    gymId: "gym-pulse",
    locationSource: "gym",
    locationName: "Pulse Club Recife",
    locationLatitude: null,
    locationLongitude: null,
    locationGoogleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Pulse+Club+Recife",
    createdAt: "2026-05-06T06:54:00",
    workoutDate: "2026-05-06",
    isWorkoutPost: true,
    streakAtPost: 32,
    likesCount: 1103,
    likedByCurrentUser: false,
    comments: [],
  },
  {
    id: "post-4",
    userId: "user-rafa",
    imageUrl:
      "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    caption: "Peito e ombro. Carga subindo devagar, tecnica primeiro.",
    workoutType: "Forca",
    gymName: "Pulse Club Recife",
    gymId: "gym-pulse",
    locationSource: "gym",
    locationName: "Pulse Club Recife",
    locationLatitude: null,
    locationLongitude: null,
    locationGoogleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Pulse+Club+Recife",
    createdAt: "2026-05-06T08:04:00",
    workoutDate: "2026-05-06",
    isWorkoutPost: true,
    streakAtPost: 9,
    likesCount: 542,
    likedByCurrentUser: false,
    comments: [],
  },
  {
    id: "post-5",
    userId: "user-bia",
    imageUrl:
      "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    caption: "5K facil antes do trabalho. O dificil era sair da cama.",
    workoutType: "Corrida",
    gymName: "Studio Flow",
    gymId: "gym-flow",
    locationSource: "gym",
    locationName: "Studio Flow",
    locationLatitude: null,
    locationLongitude: null,
    locationGoogleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Studio+Flow",
    createdAt: "2026-05-06T06:21:00",
    workoutDate: "2026-05-06",
    isWorkoutPost: true,
    streakAtPost: 5,
    likesCount: 721,
    likedByCurrentUser: false,
    comments: [],
  },
  {
    id: "post-6",
    userId: "user-ana",
    imageUrl:
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    caption: "Core e mobilidade. Treino silencioso, resultado alto.",
    workoutType: "Core",
    gymName: "Wellness Lab",
    gymId: "gym-wellness",
    locationSource: "gym",
    locationName: "Wellness Lab",
    locationLatitude: null,
    locationLongitude: null,
    locationGoogleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Wellness+Lab",
    createdAt: "2026-05-05T09:12:00",
    workoutDate: "2026-05-05",
    isWorkoutPost: true,
    streakAtPost: 4,
    likesCount: 438,
    likedByCurrentUser: false,
    comments: [],
  },
];

const stories: GymStory[] = [
  {
    id: "story-edu",
    userId: "user-edu",
    imageUrl:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    title: "Push day",
    caption: "6 dias de streak",
    createdAt: "2026-05-05T07:20:00",
    viewed: false,
    likedByCurrentUser: false,
    likesCount: 7,
    kind: "workout",
  },
  {
    id: "story-maya",
    userId: "user-maya",
    imageUrl:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    title: "Full body",
    caption: "Wellness Lab",
    createdAt: "2026-05-06T18:45:00",
    viewed: false,
    likedByCurrentUser: false,
    likesCount: 18,
    kind: "workout",
  },
  {
    id: "story-rafa",
    userId: "user-rafa",
    imageUrl:
      "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    title: "Forca",
    caption: "9 dias sem falhar",
    createdAt: "2026-05-06T08:09:00",
    viewed: false,
    likedByCurrentUser: false,
    likesCount: 11,
    kind: "workout",
  },
  {
    id: "story-bia",
    userId: "user-bia",
    imageUrl:
      "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    title: "5K",
    caption: "Corrida leve",
    createdAt: "2026-05-06T06:24:00",
    viewed: false,
    likedByCurrentUser: false,
    likesCount: 9,
    kind: "workout",
  },
  {
    id: "story-leo",
    userId: "user-leo",
    imageUrl:
      "https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=900&q=86",
    mediaType: "image",
    title: "32 dias",
    caption: "Nível lendário",
    createdAt: "2026-05-06T06:58:00",
    viewed: false,
    likedByCurrentUser: true,
    likesCount: 32,
    kind: "milestone",
  },
];

const chatMessages: ChatMessage[] = [
  {
    id: "msg-1",
    conversationId: "conv-edu-maya",
    senderId: "user-maya",
    receiverId: "user-edu",
    body: "Treino hoje no Wellness?",
    mediaUrl: null,
    mediaType: null,
    createdAt: "2026-05-06T18:50:00",
    readAt: null,
  },
  {
    id: "msg-2",
    conversationId: "conv-edu-maya",
    senderId: "user-edu",
    receiverId: "user-maya",
    body: "Vou postar depois do cardio.",
    mediaUrl: null,
    mediaType: null,
    createdAt: "2026-05-06T18:52:00",
    readAt: null,
  },
];

export function createInitialSocialState(): SocialState {
  return {
    currentUserId,
    users: structuredClone(users),
    posts: structuredClone(posts),
    stories: structuredClone(stories),
    chatMessages: structuredClone(chatMessages),
    checkInsToday: ["user-maya", "user-rafa", "user-leo", "user-bia", "user-ana"],
  };
}
