-- Auditoria/correção do pipeline de push social.
--
-- Antes deste patch:
--   * likes, comentários e mensagens criavam public.notifications;
--   * nenhuma trigger em public.notifications chamava send-push;
--   * private.dispatch_push aceitava chamadas sem autenticação de origem;
--   * não existia trilha persistente de entrega por provider.
--
-- O fluxo passa a ser:
-- evento social -> notifications -> pg_net -> send-push -> APNs + Web Push.

create extension if not exists pg_net with schema extensions;

-- Segredo interno compartilhado somente entre o banco e a Edge Function.
-- O valor nasce dentro do Vault; nunca fica versionado na migration.
do $$
begin
  if not exists (
    select 1
      from vault.decrypted_secrets
     where name = 'push_dispatch_secret'
  ) then
    perform vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'push_dispatch_secret',
      'Autentica chamadas pg_net para a Edge Function send-push'
    );
  end if;
end
$$;

-- A chave VAPID é gerada pela própria Edge Function no primeiro uso e guardada
-- cifrada no Vault. Estas RPCs são exclusivas do service_role da função.
create or replace function public.edge_push_vapid_keys()
returns text
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception 'service_role required' using errcode = '42501';
  end if;

  return (
    select decrypted_secret
      from vault.decrypted_secrets
     where name = 'push_vapid_keys'
     order by created_at desc
     limit 1
  );
end;
$$;

create or replace function public.edge_store_push_vapid_keys(p_keys text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  stored_keys text;
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception 'service_role required' using errcode = '42501';
  end if;
  if nullif(btrim(p_keys), '') is null then
    raise exception 'VAPID keys are required' using errcode = '22023';
  end if;

  -- Serializa o primeiro bootstrap para dois cold starts não criarem pares
  -- diferentes ao mesmo tempo.
  perform pg_advisory_xact_lock(hashtext('gym-circle-push-vapid-keys'));

  select decrypted_secret
    into stored_keys
    from vault.decrypted_secrets
   where name = 'push_vapid_keys'
   order by created_at desc
   limit 1;

  if stored_keys is null then
    perform vault.create_secret(
      p_keys,
      'push_vapid_keys',
      'Par VAPID JWK usado pelo Web Push do Gym Circle'
    );
    stored_keys := p_keys;
  end if;

  return stored_keys;
end;
$$;

revoke all on function public.edge_push_vapid_keys() from public, anon, authenticated;
revoke all on function public.edge_store_push_vapid_keys(text) from public, anon, authenticated;
grant execute on function public.edge_push_vapid_keys() to service_role;
grant execute on function public.edge_store_push_vapid_keys(text) to service_role;

-- A Edge Function usa esta RPC para validar o segredo enviado pelo pg_net.
create or replace function public.edge_push_dispatch_secret()
returns text
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role' then
    raise exception 'service_role required' using errcode = '42501';
  end if;

  return (
    select decrypted_secret
      from vault.decrypted_secrets
     where name = 'push_dispatch_secret'
     order by created_at desc
     limit 1
  );
end;
$$;

revoke all on function public.edge_push_dispatch_secret() from public, anon, authenticated;
grant execute on function public.edge_push_dispatch_secret() to service_role;

-- Observabilidade sem guardar token APNs ou endpoint Web Push em claro.
create table if not exists public.push_delivery_attempts (
  id bigint generated by default as identity primary key,
  notification_id uuid references public.notifications(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('apns', 'web_push')),
  target_hash text not null,
  status text not null check (status in ('sent', 'failed', 'skipped')),
  provider_code integer,
  provider_reason text,
  created_at timestamptz not null default now()
);

create index if not exists push_delivery_attempts_notification_idx
  on public.push_delivery_attempts (notification_id, created_at desc);
create index if not exists push_delivery_attempts_user_recent_idx
  on public.push_delivery_attempts (user_id, created_at desc);
create index if not exists push_delivery_attempts_failed_recent_idx
  on public.push_delivery_attempts (created_at desc)
  where status = 'failed';

alter table public.push_delivery_attempts enable row level security;
revoke all on public.push_delivery_attempts from public, anon, authenticated;
grant select, insert, update, delete on public.push_delivery_attempts to service_role;
grant usage, select on sequence public.push_delivery_attempts_id_seq to service_role;

-- Atualiza o helper existente sem mudar sua assinatura, preservando as
-- triggers de conquista/desafio. A Edge Function rejeita POST sem o header.
create or replace function private.dispatch_push(
  p_user_id uuid,
  p_kind text,
  p_title text,
  p_body text,
  p_data jsonb default '{}'::jsonb
) returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  function_url constant text :=
    'https://qajjpjmybmqqwflytcpr.supabase.co/functions/v1/send-push';
  anon_key constant text :=
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhampwam15Ym1xcXdmbHl0Y3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwOTU5MTksImV4cCI6MjA5MzY3MTkxOX0.mnwXnpMLg38LeBIoQm6gg5dc0EEEZS9F3MFQp7wXm3I';
  dispatch_secret text;
  request_id bigint;
begin
  select decrypted_secret
    into dispatch_secret
    from vault.decrypted_secrets
   where name = 'push_dispatch_secret'
   order by created_at desc
   limit 1;

  if dispatch_secret is null then
    return null;
  end if;

  select net.http_post(
    url := function_url,
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || anon_key,
      'apikey', anon_key,
      'X-Push-Dispatch-Secret', dispatch_secret
    ),
    body := jsonb_build_object(
      'user_id', p_user_id,
      'kind', p_kind,
      'title', p_title,
      'body', p_body,
      'data', coalesce(p_data, '{}'::jsonb)
    )
  ) into request_id;

  return request_id;
exception when others then
  -- Push é efeito colateral: uma indisponibilidade externa não pode desfazer
  -- a curtida, o comentário ou a mensagem original.
  return null;
end;
$$;

revoke all on function private.dispatch_push(uuid, text, text, text, jsonb)
  from public, anon, authenticated;

-- Renderiza os textos sociais no banco, no mesmo ponto que possui ator e alvo.
-- Não inclui o texto privado da mensagem/comentário na tela bloqueada.
create or replace function private.notify_social_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_name text := 'Alguém';
  object_label text := 'publicação';
  push_body text;
  push_data jsonb;
begin
  select coalesce(
           nullif(btrim(p.display_name), ''),
           case when nullif(btrim(p.username::text), '') is not null
             then '@' || p.username::text
           end,
           'Alguém'
         )
    into actor_name
    from public.profiles p
   where p.user_id = new.actor_id;

  actor_name := coalesce(actor_name, 'Alguém');

  if new.post_id is not null then
    select case
             when p.source_activity_id is not null
               or nullif(btrim(p.workout_type), '') is not null
               or coalesce(cardinality(p.workout_types), 0) > 0
               then 'treino'
             else 'publicação'
           end
      into object_label
      from public.posts p
     where p.id = new.post_id;
    object_label := coalesce(object_label, 'publicação');
  end if;

  push_body := case new.kind
    when 'new_message' then actor_name || ' te enviou uma mensagem'
    when 'like' then actor_name || ' curtiu seu ' || object_label
    when 'comment' then actor_name || ' comentou no seu ' || object_label
    when 'comment_like' then actor_name || ' curtiu seu comentário'
    when 'comment_reply' then actor_name || ' respondeu ao seu comentário'
    when 'follow' then actor_name || ' começou a seguir você'
    when 'follow_request' then actor_name || ' quer seguir você'
    when 'mention' then actor_name || ' mencionou você em um comentário'
    when 'story_like' then actor_name || ' curtiu seu story'
    when 'story_reply' then actor_name || ' respondeu ao seu story'
    when 'post_tag' then actor_name || ' marcou você em uma publicação'
    when 'story_tag' then actor_name || ' marcou você em um story'
    else null
  end;

  if push_body is null then
    return new;
  end if;

  push_data := jsonb_strip_nulls(jsonb_build_object(
    'notification_id', new.id,
    'actor_id', new.actor_id,
    'post_id', new.post_id,
    'comment_id', new.comment_id,
    'story_id', new.story_id,
    'url', case
      when new.kind = 'new_message' then '/?tab=chat'
      when new.post_id is not null then '/?post=' || new.post_id::text
      when new.story_id is not null then '/?story=' || new.story_id::text
      else '/?notifications=1'
    end
  ));

  perform private.dispatch_push(
    new.user_id,
    new.kind,
    'Gym Circle',
    push_body,
    push_data
  );

  return new;
exception when others then
  return new;
end;
$$;

drop trigger if exists notifications_after_insert_push on public.notifications;
create trigger notifications_after_insert_push
  after insert on public.notifications
  for each row
  execute function private.notify_social_push();

comment on function private.notify_social_push() is
  'Despacha push social APNs/Web Push após inserir notifications, sem bloquear o evento original.';
comment on table public.push_delivery_attempts is
  'Auditoria server-side de entrega push; alvos são armazenados apenas como SHA-256.';
