-- Sprint Push Notifications Real — payloads sociais + logs de reminder.
-- Additive/non-destructive. Não guarda tokens APNs em claro fora de
-- device_push_tokens; logs usam apenas user_id/tipo/alvo lógico.

create table if not exists public.push_delivery_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  target_id text,
  status text not null check (status in ('sent', 'failed', 'skipped')),
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists push_delivery_logs_user_type_target_idx
  on public.push_delivery_logs (user_id, type, target_id, created_at desc);

create index if not exists push_delivery_logs_reminder_recent_idx
  on public.push_delivery_logs (user_id, created_at desc)
  where type = 'daily_activity_reminder';

alter table public.push_delivery_logs enable row level security;
revoke all on public.push_delivery_logs from public, anon, authenticated;
grant select, insert, update, delete on public.push_delivery_logs to service_role;
grant usage, select on sequence public.push_delivery_logs_id_seq to service_role;

create or replace function private.notify_social_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_name text := 'Alguém';
  object_label text := 'publicação';
  push_title text;
  push_body text;
  push_kind text;
  push_data jsonb;
  conversation_id uuid;
  deep_link text;
  web_url text;
begin
  -- Defesa extra: triggers/notifications não devem virar push para si mesmo,
  -- nem atravessar bloqueios/mutes já existentes no produto.
  if new.actor_id is null or new.user_id = new.actor_id then
    return new;
  end if;

  if exists (
    select 1
      from public.user_blocks blocked
     where (
       blocked.blocker_id = new.user_id
       and blocked.blocked_id = new.actor_id
     )
        or (
       blocked.blocker_id = new.actor_id
       and blocked.blocked_id = new.user_id
     )
  ) then
    return new;
  end if;

  if new.post_id is not null and exists (
    select 1
      from public.post_mutes mute_row
     where mute_row.user_id = new.user_id
       and mute_row.muted_user_id = new.actor_id
  ) then
    return new;
  end if;

  if new.story_id is not null and exists (
    select 1
      from public.story_mutes mute_row
     where mute_row.user_id = new.user_id
       and mute_row.muted_user_id = new.actor_id
  ) then
    return new;
  end if;

  select coalesce(
           nullif(btrim(p.display_name), ''),
           case when nullif(btrim(p.username::text), '') is not null
             then '@' || p.username::text
           end,
           'Alguém'
         )
    into actor_name
    from public.profiles p
   where p.user_id = new.actor_id;

  actor_name := coalesce(actor_name, 'Alguém');

  if new.post_id is not null then
    select case
             when p.source_activity_id is not null
               or nullif(btrim(p.workout_type), '') is not null
               or coalesce(cardinality(p.workout_types), 0) > 0
               then 'treino'
             else 'publicação'
           end
      into object_label
      from public.posts p
     where p.id = new.post_id;
    object_label := coalesce(object_label, 'publicação');
  end if;

  if new.kind = 'new_message' then
    select dm.conversation_id
      into conversation_id
      from public.direct_messages dm
     where dm.sender_id = new.actor_id
       and (
         dm.receiver_id = new.user_id
         or (
           dm.receiver_id is null
           and exists (
             select 1
               from public.conversation_participants cp
              where cp.conversation_id = dm.conversation_id
                and cp.user_id = new.user_id
                and cp.deleted_at is null
           )
         )
       )
     order by dm.created_at desc
     limit 1;
  end if;

  push_kind := case new.kind
    when 'new_message' then 'message'
    when 'like' then 'post_like'
    when 'comment' then 'post_comment'
    when 'comment_reply' then 'post_comment'
    when 'mention' then 'post_comment'
    else new.kind
  end;

  push_title := case new.kind
    when 'new_message' then 'Nova mensagem'
    when 'like' then 'Nova curtida'
    when 'comment' then 'Novo comentário'
    when 'comment_reply' then 'Nova resposta'
    when 'comment_like' then 'Curtida no comentário'
    when 'follow' then 'Novo seguidor'
    when 'follow_request' then 'Nova solicitação'
    when 'mention' then 'Você foi mencionado'
    when 'story_like' then 'Nova curtida'
    when 'story_reply' then 'Nova resposta'
    when 'post_tag' then 'Você foi marcado'
    when 'story_tag' then 'Você foi marcado'
    else 'Gym Circle'
  end;

  push_body := case new.kind
    when 'new_message' then actor_name || ' te enviou uma mensagem.'
    when 'like' then actor_name || ' curtiu seu ' || object_label || '.'
    when 'comment' then actor_name || ' comentou no seu ' || object_label || '.'
    when 'comment_like' then actor_name || ' curtiu seu comentário.'
    when 'comment_reply' then actor_name || ' respondeu ao seu comentário.'
    when 'follow' then actor_name || ' começou a seguir você.'
    when 'follow_request' then actor_name || ' quer seguir você.'
    when 'mention' then actor_name || ' mencionou você em um comentário.'
    when 'story_like' then actor_name || ' curtiu seu story.'
    when 'story_reply' then actor_name || ' respondeu ao seu story.'
    when 'post_tag' then actor_name || ' marcou você em uma publicação.'
    when 'story_tag' then actor_name || ' marcou você em um story.'
    else null
  end;

  if push_body is null then
    return new;
  end if;

  deep_link := case
    when new.kind = 'new_message' and conversation_id is not null
      then 'gymcircle://chat/' || conversation_id::text
    when new.kind = 'new_message'
      then 'gymcircle://chat'
    when new.post_id is not null and new.kind in ('comment', 'comment_reply', 'mention')
      then 'gymcircle://post/' || new.post_id::text || '?comments=true'
    when new.post_id is not null
      then 'gymcircle://post/' || new.post_id::text
    when new.story_id is not null
      then 'gymcircle://story/' || new.story_id::text
    else 'gymcircle://notifications'
  end;

  web_url := case
    when new.kind = 'new_message' then '/?tab=chat'
    when new.post_id is not null and new.kind in ('comment', 'comment_reply', 'mention')
      then '/?post=' || new.post_id::text || '&comments=1'
    when new.post_id is not null then '/?post=' || new.post_id::text
    when new.story_id is not null then '/?story=' || new.story_id::text
    else '/?notifications=1'
  end;

  push_data := jsonb_strip_nulls(jsonb_build_object(
    'notification_id', new.id::text,
    'actor_id', new.actor_id::text,
    'post_id', case when new.post_id is not null then new.post_id::text end,
    'comment_id', case when new.comment_id is not null then new.comment_id::text end,
    'story_id', case when new.story_id is not null then new.story_id::text end,
    'conversation_id', case when conversation_id is not null then conversation_id::text end,
    'type', push_kind,
    'deep_link', deep_link,
    'url', web_url,
    'collapse_id', coalesce(
      case when conversation_id is not null then 'conversation:' || conversation_id::text end,
      case when new.post_id is not null then 'post:' || new.post_id::text || ':' || push_kind end,
      new.kind
    )
  ));

  perform private.dispatch_push(
    new.user_id,
    push_kind,
    push_title,
    push_body,
    push_data
  );

  return new;
exception when others then
  return new;
end;
$$;

drop trigger if exists notifications_after_insert_push on public.notifications;
create trigger notifications_after_insert_push
  after insert on public.notifications
  for each row
  execute function private.notify_social_push();

revoke all on function private.notify_social_push() from public, anon, authenticated;

comment on table public.push_delivery_logs is
  'Logs server-side para campanhas/reminders push; não armazena token APNs.';
comment on function private.notify_social_push() is
  'Despacha push social APNs/Web Push com tipo, título, collapse id e deep link.';
