-- Amplia o catálogo aprovado com exercícios básicos e variações comuns.
-- Idempotente: pode rodar mais de uma vez e também corrige nomes em inglês
-- dos itens que nasceram das primeiras planilhas/OCR.

with seed (
  slug,
  name_pt,
  name_en,
  aliases,
  muscle_group,
  secondary_groups,
  equipment,
  description_pt,
  description_en,
  instructions_pt,
  instructions_en,
  video_search_query
) as (
  values
    (
      'supino-reto-barra',
      'Supino reto barra',
      'Barbell Bench Press',
      array['supino reto', 'supino livre', 'bench press', 'barbell bench press'],
      'chest',
      array['triceps', 'shoulders'],
      array['barbell', 'bench'],
      'Supino livre em banco reto, indicado para peitoral com participação de tríceps e ombros.',
      'Free-weight bench press on a flat bench, targeting chest with triceps and shoulders assisting.',
      array['Deite com pés firmes e escápulas encaixadas.', 'Desça a barra com controle até a linha do peito.', 'Empurre mantendo punhos alinhados e sem perder estabilidade.'],
      array['Lie with feet planted and shoulder blades set.', 'Lower the bar under control toward the chest line.', 'Press while keeping wrists stacked and the body stable.'],
      'barbell bench press proper form'
    ),
    (
      'supino-reto-halteres',
      'Supino reto halteres',
      'Dumbbell Bench Press',
      array['supino halteres', 'supino livre halteres', 'dumbbell bench press'],
      'chest',
      array['triceps', 'shoulders'],
      array['dumbbells', 'bench'],
      'Variação livre do supino reto com halteres, permitindo maior amplitude e controle unilateral.',
      'Dumbbell flat bench variation that allows more range of motion and unilateral control.',
      array['Comece com halteres alinhados ao peito.', 'Desça mantendo cotovelos controlados.', 'Empurre até quase estender os cotovelos sem bater os halteres.'],
      array['Start with dumbbells aligned over the chest.', 'Lower while controlling the elbows.', 'Press up without slamming the dumbbells together.'],
      'dumbbell bench press proper form'
    ),
    (
      'supino-inclinado-barra',
      'Supino inclinado barra',
      'Incline Barbell Bench Press',
      array['supino inclinado', 'incline bench press', 'incline barbell press'],
      'chest',
      array['shoulders', 'triceps'],
      array['barbell', 'incline bench'],
      'Supino livre em banco inclinado com ênfase na porção superior do peitoral.',
      'Free-weight incline press emphasizing the upper chest.',
      array['Use inclinação moderada.', 'Desça a barra na parte alta do peito.', 'Empurre sem transformar o movimento em desenvolvimento de ombro.'],
      array['Use a moderate incline.', 'Lower the bar toward the upper chest.', 'Press without turning it into a shoulder press.'],
      'incline barbell bench press proper form'
    ),
    (
      'supino-inclinado-halteres',
      'Supino inclinado halteres',
      'Incline Dumbbell Bench Press',
      array['supino inclinado com halteres', 'incline dumbbell bench press'],
      'chest',
      array['shoulders', 'triceps'],
      array['dumbbells', 'incline bench'],
      'Variação inclinada com halteres para peitoral superior e controle de amplitude.',
      'Incline dumbbell press for upper chest with controlled range of motion.',
      array['Apoie as costas no banco inclinado.', 'Desça os halteres de forma simétrica.', 'Suba mantendo cotovelos abaixo da linha dos ombros.'],
      array['Set your back on the incline bench.', 'Lower the dumbbells symmetrically.', 'Press while keeping elbows below the shoulder line.'],
      'incline dumbbell bench press proper form'
    ),
    (
      'supino-declinado-barra',
      'Supino declinado barra',
      'Decline Barbell Bench Press',
      array['supino declinado', 'decline bench press'],
      'chest',
      array['triceps', 'shoulders'],
      array['barbell', 'decline bench'],
      'Supino em banco declinado, usado como variação para peitoral inferior.',
      'Decline bench press variation commonly used for lower chest emphasis.',
      array['Prenda os pés com segurança.', 'Controle a descida na linha inferior do peito.', 'Empurre mantendo tronco fixo no banco.'],
      array['Secure the feet safely.', 'Control the bar toward the lower chest line.', 'Press while keeping the torso fixed on the bench.'],
      'decline barbell bench press proper form'
    ),
    (
      'supino-maquina',
      'Supino máquina',
      'Machine Chest Press',
      array['chest press', 'machine chest press', 'supino sentado máquina'],
      'chest',
      array['triceps', 'shoulders'],
      array['machine'],
      'Empurrada horizontal guiada para peitoral, tríceps e deltoides.',
      'Guided horizontal press for chest, triceps and anterior deltoids.',
      array['Ajuste o banco para as manoplas ficarem na linha do peito.', 'Empurre sem tirar as costas do apoio.', 'Volte controlando a carga.'],
      array['Set the seat so handles align with the chest.', 'Press without lifting your back from the pad.', 'Return the load under control.'],
      'machine chest press proper form'
    ),
    (
      'crucifixo-cabo',
      'Crucifixo no cabo',
      'Cable Fly',
      array['cable fly', 'cabo crucifixo', 'cross over fly'],
      'chest',
      array['shoulders'],
      array['cable'],
      'Adução dos braços no cabo para peitoral, mantendo tensão constante.',
      'Cable chest fly keeping continuous tension through the movement.',
      array['Ajuste as polias na altura desejada.', 'Mantenha cotovelos levemente flexionados.', 'Aproxime as mãos sem perder controle na volta.'],
      array['Set the pulleys at the desired height.', 'Keep elbows slightly bent.', 'Bring hands together without losing control on the return.'],
      'cable chest fly proper form'
    ),
    (
      'flexao-de-bracos',
      'Flexão de braços',
      'Push-up',
      array['flexao', 'push up', 'push-up'],
      'chest',
      array['triceps', 'shoulders', 'abdomen'],
      array['bodyweight'],
      'Exercício de peso corporal para peitoral, tríceps, ombros e core.',
      'Bodyweight exercise for chest, triceps, shoulders and core.',
      array['Mantenha o corpo alinhado.', 'Desça com cotovelos controlados.', 'Empurre o chão sem perder o tronco firme.'],
      array['Keep the body in a straight line.', 'Lower with controlled elbows.', 'Push the floor away while keeping the trunk braced.'],
      'push up proper form'
    ),
    (
      'barra-fixa',
      'Barra fixa',
      'Pull-up',
      array['pull up', 'pull-up', 'chin up', 'chin-up'],
      'back',
      array['biceps'],
      array['bodyweight', 'pull-up bar'],
      'Puxada vertical com peso corporal para dorsais e bíceps.',
      'Bodyweight vertical pull for lats and biceps.',
      array['Comece pendurado com ombros ativos.', 'Puxe o peito em direção à barra.', 'Desça controlando até a amplitude segura.'],
      array['Start hanging with active shoulders.', 'Pull the chest toward the bar.', 'Lower under control to a safe range.'],
      'pull up proper form'
    ),
    (
      'puxada-frente-barra',
      'Puxada frente barra',
      'Wide-Grip Lat Pulldown',
      array['puxada aberta', 'lat pulldown', 'wide grip lat pulldown'],
      'back',
      array['biceps'],
      array['cable'],
      'Puxada vertical na polia com barra, focada em dorsais.',
      'Cable vertical pull with a bar, focused on the lats.',
      array['Segure a barra com pegada confortável.', 'Puxe os cotovelos para baixo.', 'Evite jogar o tronco para trás.'],
      array['Hold the bar with a comfortable grip.', 'Drive elbows downward.', 'Avoid leaning the torso back excessively.'],
      'wide grip lat pulldown proper form'
    ),
    (
      'puxada-pegada-neutra',
      'Puxada pegada neutra',
      'Neutral-Grip Lat Pulldown',
      array['puxada triangulo', 'neutral grip pulldown', 'close grip lat pulldown'],
      'back',
      array['biceps'],
      array['cable'],
      'Puxada vertical com pegada neutra, normalmente com triângulo ou manopla paralela.',
      'Lat pulldown with a neutral grip, usually using a close parallel handle.',
      array['Sente com joelhos firmes no apoio.', 'Conduza cotovelos para baixo e para trás.', 'Retorne controlando a escápula.'],
      array['Sit with knees secured under the pad.', 'Drive elbows down and back.', 'Return while controlling the shoulder blades.'],
      'neutral grip lat pulldown proper form'
    ),
    (
      'remada-baixa-cabo',
      'Remada baixa cabo',
      'Seated Cable Row',
      array['remada baixa', 'seated row', 'cable row'],
      'back',
      array['biceps'],
      array['cable'],
      'Remada sentada na polia para dorsais, romboides e controle escapular.',
      'Seated cable row for lats, rhomboids and scapular control.',
      array['Sente alto com coluna neutra.', 'Puxe o cabo levando cotovelos para trás.', 'Volte sem arredondar a lombar.'],
      array['Sit tall with a neutral spine.', 'Pull the handle by driving elbows back.', 'Return without rounding the lower back.'],
      'seated cable row proper form'
    ),
    (
      'remada-curva-barra',
      'Remada curva barra',
      'Barbell Bent-Over Row',
      array['barbell row', 'bent over row', 'remada barra'],
      'back',
      array['biceps', 'hamstrings'],
      array['barbell'],
      'Remada inclinada com barra e coluna neutra.',
      'Bent-over barbell row performed with a neutral spine.',
      array['Incline o tronco com quadril para trás.', 'Puxe a barra em direção ao abdômen.', 'Mantenha a coluna estável durante a série.'],
      array['Hinge at the hips with the torso inclined.', 'Pull the bar toward the abdomen.', 'Keep the spine stable throughout the set.'],
      'barbell bent over row proper form'
    ),
    (
      'remada-unilateral-halter-serrote',
      'Remada unilateral halter (serrote)',
      'One-Arm Dumbbell Row',
      array['serrote', 'one arm dumbbell row', 'single arm row'],
      'back',
      array['biceps'],
      array['dumbbell', 'bench'],
      'Remada unilateral apoiada com halter, sem girar excessivamente o tronco.',
      'Supported one-arm dumbbell row without excessive torso rotation.',
      array['Apoie uma mão e um joelho no banco.', 'Puxe o halter levando o cotovelo para trás.', 'Desça sem perder a estabilidade do tronco.'],
      array['Support one hand and knee on the bench.', 'Pull the dumbbell by driving the elbow back.', 'Lower without losing trunk stability.'],
      'one arm dumbbell row proper form'
    ),
    (
      'levantamento-terra',
      'Levantamento terra',
      'Conventional Deadlift',
      array['terra', 'deadlift', 'conventional deadlift'],
      'hamstrings',
      array['glutes', 'back', 'quadriceps'],
      array['barbell'],
      'Levantamento do solo com barra, usando quadril, posteriores, glúteos e costas.',
      'Barbell lift from the floor using hips, hamstrings, glutes and back.',
      array['Posicione a barra sobre o meio do pé.', 'Trave o tronco antes de tirar a barra do chão.', 'Suba estendendo quadril e joelhos juntos.'],
      array['Set the bar over the midfoot.', 'Brace before pulling the bar from the floor.', 'Stand by extending hips and knees together.'],
      'conventional deadlift proper form'
    ),
    (
      'desenvolvimento-militar-barra',
      'Desenvolvimento militar barra',
      'Barbell Overhead Press',
      array['desenvolvimento barra', 'military press', 'overhead press'],
      'shoulders',
      array['triceps'],
      array['barbell'],
      'Empurrada vertical livre para deltoides e tríceps.',
      'Free-weight vertical press for deltoids and triceps.',
      array['Comece com a barra próxima aos ombros.', 'Contraia o abdômen e glúteos.', 'Empurre acima da cabeça sem arquear demais a lombar.'],
      array['Start with the bar near the shoulders.', 'Brace the abs and glutes.', 'Press overhead without over-arching the lower back.'],
      'barbell overhead press proper form'
    ),
    (
      'desenvolvimento-halteres',
      'Desenvolvimento halteres',
      'Dumbbell Shoulder Press',
      array['shoulder press', 'dumbbell shoulder press', 'desenvolvimento ombro'],
      'shoulders',
      array['triceps'],
      array['dumbbells'],
      'Empurrada vertical com halteres para ombros, podendo ser sentada ou em pé.',
      'Dumbbell vertical press for shoulders, seated or standing.',
      array['Mantenha halteres próximos aos ombros.', 'Empurre verticalmente com controle.', 'Desça sem deixar cotovelos caírem demais.'],
      array['Keep dumbbells close to the shoulders.', 'Press vertically with control.', 'Lower without letting the elbows drop too far.'],
      'dumbbell shoulder press proper form'
    ),
    (
      'elevacao-lateral-cabo',
      'Elevação lateral cabo',
      'Cable Lateral Raise',
      array['lateral raise cable', 'cable lateral raise'],
      'shoulders',
      array['trapezius'],
      array['cable'],
      'Elevação lateral na polia para deltoide medial com tensão constante.',
      'Cable lateral raise for the medial deltoid with constant tension.',
      array['Posicione a polia baixa ao lado do corpo.', 'Eleve o braço até próximo da linha do ombro.', 'Volte devagar sem relaxar totalmente.'],
      array['Set the pulley low at your side.', 'Raise the arm near shoulder height.', 'Return slowly without fully relaxing.'],
      'cable lateral raise proper form'
    ),
    (
      'elevacao-frontal-halteres',
      'Elevação frontal halteres',
      'Dumbbell Front Raise',
      array['front raise', 'dumbbell front raise'],
      'shoulders',
      array[]::text[],
      array['dumbbells'],
      'Elevação dos braços à frente para deltoide anterior.',
      'Forward arm raise targeting the anterior deltoid.',
      array['Segure os halteres à frente das coxas.', 'Eleve até a linha dos ombros.', 'Evite balançar o tronco.'],
      array['Hold dumbbells in front of the thighs.', 'Raise to shoulder height.', 'Avoid swinging the torso.'],
      'dumbbell front raise proper form'
    ),
    (
      'face-pull',
      'Face pull',
      'Face Pull',
      array['facepull', 'puxada rosto', 'rear delt rope pull'],
      'shoulders',
      array['trapezius', 'back'],
      array['cable', 'rope'],
      'Puxada na corda para deltoide posterior, trapézio e saúde escapular.',
      'Rope pull for rear delts, traps and scapular control.',
      array['Use a corda na altura do rosto.', 'Puxe separando as mãos e levando cotovelos para trás.', 'Controle a volta mantendo ombros baixos.'],
      array['Set the rope around face height.', 'Pull by spreading the hands and driving elbows back.', 'Control the return while keeping shoulders down.'],
      'face pull proper form'
    ),
    (
      'agachamento-livre-barra',
      'Agachamento livre barra',
      'Barbell Back Squat',
      array['agachamento livre', 'back squat', 'barbell squat'],
      'quadriceps',
      array['glutes', 'hamstrings'],
      array['barbell', 'rack'],
      'Agachamento livre com barra nas costas para pernas e glúteos.',
      'Free-weight barbell squat for legs and glutes.',
      array['Apoie a barra de forma segura nas costas.', 'Desça mantendo joelhos alinhados aos pés.', 'Suba empurrando o chão e mantendo tronco firme.'],
      array['Set the bar securely on the upper back.', 'Descend with knees tracking over the feet.', 'Stand by pushing the floor while keeping the torso braced.'],
      'barbell back squat proper form'
    ),
    (
      'agachamento-frontal-barra',
      'Agachamento frontal barra',
      'Barbell Front Squat',
      array['front squat', 'agachamento frontal'],
      'quadriceps',
      array['glutes', 'abdomen'],
      array['barbell', 'rack'],
      'Agachamento com barra à frente do corpo, exigindo tronco ereto e core ativo.',
      'Squat with the bar in front, requiring upright posture and strong core bracing.',
      array['Apoie a barra nos ombros à frente.', 'Mantenha cotovelos altos.', 'Desça com tronco ereto e joelhos alinhados.'],
      array['Rest the bar on the front of the shoulders.', 'Keep elbows high.', 'Descend with an upright torso and knees tracking well.'],
      'front squat proper form'
    ),
    (
      'hack-squat',
      'Hack squat',
      'Hack Squat',
      array['agachamento hack', 'hack machine squat'],
      'quadriceps',
      array['glutes'],
      array['machine'],
      'Agachamento guiado na máquina hack, com foco em quadríceps.',
      'Machine-guided squat emphasizing the quadriceps.',
      array['Apoie costas e ombros na máquina.', 'Desça controlando joelhos e quadril.', 'Empurre a plataforma sem travar agressivamente os joelhos.'],
      array['Set back and shoulders against the machine.', 'Lower while controlling knees and hips.', 'Push the platform without aggressively locking the knees.'],
      'hack squat proper form'
    ),
    (
      'leg-press-45',
      'Leg press 45°',
      '45-Degree Leg Press',
      array['leg press', 'leg press 45', '45 degree leg press'],
      'quadriceps',
      array['glutes', 'hamstrings'],
      array['leg press'],
      'Empurrada na plataforma 45 graus para quadríceps, glúteos e posteriores.',
      '45-degree platform press for quads, glutes and hamstrings.',
      array['Ajuste os pés na plataforma.', 'Desça até amplitude segura sem tirar lombar do apoio.', 'Empurre sem travar os joelhos com força.'],
      array['Set feet on the platform.', 'Lower to a safe range without lifting the lower back.', 'Press without forcefully locking the knees.'],
      '45 degree leg press proper form'
    ),
    (
      'stiff-barra',
      'Stiff barra',
      'Barbell Romanian Deadlift',
      array['stiff', 'rdl', 'romanian deadlift'],
      'hamstrings',
      array['glutes', 'back'],
      array['barbell'],
      'Dobradiça de quadril com barra para posteriores e glúteos.',
      'Hip hinge with a barbell for hamstrings and glutes.',
      array['Segure a barra próxima ao corpo.', 'Leve o quadril para trás com joelhos levemente flexionados.', 'Suba contraindo glúteos sem arredondar a coluna.'],
      array['Keep the bar close to the body.', 'Push hips back with slightly bent knees.', 'Stand by squeezing glutes without rounding the spine.'],
      'barbell romanian deadlift proper form'
    ),
    (
      'hip-thrust-barra',
      'Hip thrust barra',
      'Barbell Hip Thrust',
      array['hip thrust', 'elevação pélvica barra'],
      'glutes',
      array['hamstrings'],
      array['barbell', 'bench'],
      'Extensão de quadril com barra e costas apoiadas no banco para glúteos.',
      'Barbell hip extension with upper back on a bench for glutes.',
      array['Apoie a parte alta das costas no banco.', 'Mantenha a barra protegida sobre o quadril.', 'Eleve até alinhar tronco e coxas sem hiperextender a lombar.'],
      array['Rest the upper back on the bench.', 'Pad and position the bar over the hips.', 'Lift until torso and thighs align without overextending the lower back.'],
      'barbell hip thrust proper form'
    ),
    (
      'afundo-bulgaro',
      'Afundo búlgaro',
      'Bulgarian Split Squat',
      array['bulgarian split squat', 'agachamento bulgaro'],
      'quadriceps',
      array['glutes', 'hamstrings'],
      array['dumbbells', 'bench'],
      'Agachamento unilateral com pé traseiro apoiado no banco.',
      'Single-leg squat variation with the rear foot elevated on a bench.',
      array['Apoie o pé de trás no banco.', 'Desça mantendo joelho da frente alinhado.', 'Suba com controle sem perder equilíbrio.'],
      array['Place the rear foot on the bench.', 'Lower with the front knee tracking well.', 'Stand with control without losing balance.'],
      'bulgarian split squat proper form'
    ),
    (
      'avanco-caminhando',
      'Avanço caminhando',
      'Walking Lunge',
      array['avanço', 'passada', 'walking lunge', 'lunge'],
      'quadriceps',
      array['glutes', 'hamstrings'],
      array['bodyweight', 'dumbbells'],
      'Passadas alternadas para quadríceps, glúteos e equilíbrio.',
      'Alternating lunges for quads, glutes and balance.',
      array['Dê um passo à frente controlado.', 'Desça até amplitude segura.', 'Empurre o chão e avance para a próxima repetição.'],
      array['Step forward under control.', 'Lower to a safe range.', 'Push the floor and move into the next repetition.'],
      'walking lunge proper form'
    ),
    (
      'cadeira-abdutora',
      'Cadeira abdutora',
      'Hip Abductor Machine',
      array['abdutora', 'abductor machine', 'hip abduction'],
      'glutes',
      array[]::text[],
      array['machine'],
      'Abdução de quadril na máquina para glúteos médio e mínimo.',
      'Machine hip abduction for glute medius and minimus.',
      array['Ajuste o banco e apoios.', 'Abra as pernas sem jogar o tronco.', 'Volte controlando a carga.'],
      array['Adjust seat and pads.', 'Open the legs without throwing the torso.', 'Return the load under control.'],
      'hip abductor machine proper form'
    ),
    (
      'panturrilha-em-pe-maquina',
      'Panturrilha em pé máquina',
      'Standing Calf Raise Machine',
      array['gemeos em pe', 'standing calf raise', 'calf raise machine'],
      'calves',
      array[]::text[],
      array['machine'],
      'Flexão plantar em pé na máquina para panturrilhas.',
      'Standing machine plantar flexion for calves.',
      array['Apoie a ponta dos pés na plataforma.', 'Desça sentindo alongamento confortável.', 'Suba contraindo panturrilhas sem impulso.'],
      array['Place the balls of the feet on the platform.', 'Lower to a comfortable stretch.', 'Rise by squeezing calves without bouncing.'],
      'standing calf raise machine proper form'
    ),
    (
      'panturrilha-sentado-maquina',
      'Panturrilha sentado máquina',
      'Seated Calf Raise',
      array['gemeos sentado', 'seated calf raise'],
      'calves',
      array[]::text[],
      array['machine'],
      'Flexão plantar sentado com foco em panturrilhas.',
      'Seated plantar flexion focused on calves.',
      array['Posicione o apoio sobre as coxas.', 'Desça os calcanhares com controle.', 'Suba até contrair as panturrilhas.'],
      array['Set the pad over the thighs.', 'Lower the heels under control.', 'Raise until calves contract.'],
      'seated calf raise proper form'
    ),
    (
      'rosca-direta-barra',
      'Rosca direta barra',
      'Barbell Curl',
      array['barbell curl', 'rosca barra reta', 'biceps curl'],
      'biceps',
      array['forearms'],
      array['barbell'],
      'Flexão de cotovelos com barra para bíceps.',
      'Barbell elbow flexion for biceps.',
      array['Segure a barra com pegada supinada.', 'Flexione cotovelos sem jogar o tronco.', 'Desça controlando até quase estender.'],
      array['Hold the bar with an underhand grip.', 'Curl without swinging the torso.', 'Lower under control until nearly extended.'],
      'barbell curl proper form'
    ),
    (
      'rosca-alternada-halteres',
      'Rosca alternada halteres',
      'Alternating Dumbbell Curl',
      array['rosca alternada', 'alternating dumbbell curl'],
      'biceps',
      array['forearms'],
      array['dumbbells'],
      'Rosca unilateral alternada com halteres.',
      'Alternating unilateral dumbbell curl.',
      array['Mantenha cotovelos perto do corpo.', 'Flexione um braço por vez.', 'Controle a descida antes de alternar.'],
      array['Keep elbows close to the body.', 'Curl one arm at a time.', 'Control the lowering before switching.'],
      'alternating dumbbell curl proper form'
    ),
    (
      'rosca-inclinada-halteres',
      'Rosca inclinada halteres',
      'Incline Dumbbell Curl',
      array['incline curl', 'rosca inclinado'],
      'biceps',
      array['forearms'],
      array['dumbbells', 'incline bench'],
      'Rosca com halteres em banco inclinado, alongando mais o bíceps.',
      'Dumbbell curl on an incline bench, increasing biceps stretch.',
      array['Apoie as costas no banco inclinado.', 'Deixe os braços descerem naturalmente.', 'Flexione sem mover os ombros para frente.'],
      array['Rest the back on the incline bench.', 'Let the arms hang naturally.', 'Curl without moving shoulders forward.'],
      'incline dumbbell curl proper form'
    ),
    (
      'triceps-polia-corda',
      'Tríceps polia corda',
      'Rope Triceps Pushdown',
      array['triceps corda', 'rope pushdown', 'triceps rope pushdown'],
      'triceps',
      array['forearms'],
      array['cable', 'rope'],
      'Extensão de cotovelos na polia usando corda.',
      'Cable elbow extension using a rope attachment.',
      array['Mantenha cotovelos ao lado do corpo.', 'Empurre a corda para baixo e separe levemente as pontas.', 'Volte sem deixar ombros subirem.'],
      array['Keep elbows by the sides.', 'Push the rope down and slightly separate the ends.', 'Return without letting shoulders rise.'],
      'rope triceps pushdown proper form'
    ),
    (
      'triceps-frances-halter',
      'Tríceps francês halter',
      'Dumbbell Overhead Triceps Extension',
      array['triceps overhead', 'overhead triceps extension', 'frances halter'],
      'triceps',
      array['shoulders'],
      array['dumbbell'],
      'Extensão de cotovelos acima da cabeça com halter.',
      'Overhead elbow extension with a dumbbell.',
      array['Segure o halter acima da cabeça.', 'Flexione cotovelos mantendo braços estáveis.', 'Estenda sem abrir demais os cotovelos.'],
      array['Hold the dumbbell overhead.', 'Bend elbows while keeping upper arms stable.', 'Extend without flaring elbows too much.'],
      'dumbbell overhead triceps extension proper form'
    ),
    (
      'prancha',
      'Prancha',
      'Plank',
      array['plank'],
      'abdomen',
      array['glutes', 'shoulders'],
      array['bodyweight'],
      'Isometria para core, glúteos e estabilidade de ombros.',
      'Isometric hold for core, glutes and shoulder stability.',
      array['Apoie antebraços e pés.', 'Mantenha corpo alinhado.', 'Respire sem deixar quadril cair.'],
      array['Support on forearms and feet.', 'Keep the body aligned.', 'Breathe without letting hips drop.'],
      'plank proper form'
    ),
    (
      'abdominal-crunch',
      'Abdominal crunch',
      'Crunch',
      array['crunch', 'abdominal solo'],
      'abdomen',
      array[]::text[],
      array['bodyweight'],
      'Flexão controlada do tronco para abdômen.',
      'Controlled trunk flexion for abs.',
      array['Deite com joelhos flexionados.', 'Eleve a parte alta das costas sem puxar o pescoço.', 'Volte controlando.'],
      array['Lie with knees bent.', 'Lift the upper back without pulling the neck.', 'Return under control.'],
      'crunch proper form'
    ),
    (
      'elevacao-de-pernas-suspenso',
      'Elevação de pernas suspenso',
      'Hanging Leg Raise',
      array['leg raise', 'hanging leg raise', 'elevação de pernas'],
      'abdomen',
      array['hip flexors'],
      array['bodyweight', 'pull-up bar'],
      'Elevação das pernas pendurado para abdômen e flexores de quadril.',
      'Hanging leg raise for abs and hip flexors.',
      array['Pendure com ombros ativos.', 'Eleve pernas ou joelhos sem balançar.', 'Desça controlando o tronco.'],
      array['Hang with active shoulders.', 'Raise legs or knees without swinging.', 'Lower while controlling the trunk.'],
      'hanging leg raise proper form'
    ),
    (
      'abdominal-cabo',
      'Abdominal no cabo',
      'Cable Crunch',
      array['cable crunch', 'crunch cabo'],
      'abdomen',
      array[]::text[],
      array['cable', 'rope'],
      'Flexão do tronco ajoelhado na polia para abdômen.',
      'Kneeling cable trunk flexion for abs.',
      array['Ajoelhe segurando a corda.', 'Flexione o tronco aproximando costelas do quadril.', 'Volte sem perder tensão no abdômen.'],
      array['Kneel while holding the rope.', 'Flex the trunk by bringing ribs toward hips.', 'Return without losing abdominal tension.'],
      'cable crunch proper form'
    )
)
insert into public.workout_exercise_catalog (
  slug,
  name_pt,
  name_en,
  aliases,
  primary_muscle_group_slug,
  secondary_muscle_group_slugs,
  equipment,
  description_pt,
  description_en,
  instructions_pt,
  instructions_en,
  video_search_query,
  status
)
select
  slug,
  name_pt,
  name_en,
  aliases,
  muscle_group,
  secondary_groups,
  equipment,
  description_pt,
  description_en,
  instructions_pt,
  instructions_en,
  video_search_query,
  'approved'
from seed
on conflict (slug) do update set
  name_pt = excluded.name_pt,
  name_en = excluded.name_en,
  aliases = excluded.aliases,
  primary_muscle_group_slug = excluded.primary_muscle_group_slug,
  secondary_muscle_group_slugs = excluded.secondary_muscle_group_slugs,
  equipment = excluded.equipment,
  description_pt = excluded.description_pt,
  description_en = excluded.description_en,
  instructions_pt = excluded.instructions_pt,
  instructions_en = excluded.instructions_en,
  video_search_query = excluded.video_search_query,
  status = excluded.status,
  updated_at = now();
